
mqtt:
  host: 192.168.1.1
  port: 1883
  publisher: pulse-sensors
  user: hass

homeassistant:
  device-uuid: 47f8e41c-bfb3-4e5c-b383-515eb0f073da
  discovery:
    prefix: homeassistant
  component: sensor

sensors:
  - name: Hausstrom
    pulses-per-kwh: 6400
    guid: dbfb786d-3167-439e-9481-db3ada3a9109
    counters:
      - name: main
  - name: Heizstrom
    pulses-per-kwh: 500
    guid: ef974bc8-e7f2-4037-8e4b-9f5ee0f063d0
    counters:
      - name: T1
        type: day
      - name: T2

times:
  summer:
    start:
      day: 1
      month: 4
    day:
      from: 7
      to: 20
  winter:
    start:
      day: 1
      month: 10
    day:
      from: 7
      to: 21
